export const OPERATOR_TERMS = {
  session: 'сессия',
  incident: 'инцидент',
  tap: 'кран',
  system: 'система',
  reader: 'считыватель',
  screen: 'экран',
};

export const INCIDENT_COPY = {
  actionForm: 'Фиксация действия',
  actionFormTitle: 'Фиксация действия оператора',
  actionLayer: 'Действия оператора по инцидентам',
  detailsPanel: 'Детали инцидента',
  systemLabel: 'Система',
  impact: 'Влияние',
  owner: 'Ответственный оператор',
  ownerServer: 'Ответственный в системе',
  stateFlow: 'Ход инцидента',
  openDetails: 'Посмотреть детали',
  openTap: 'Перейти к крану',
  openSession: 'Перейти к сессии',
  openSystem: 'Проверить систему',
  refreshQueue: 'Обновить список',
  noIncidentsFiltered: 'По выбранным условиям инциденты не найдены.',
  noIncidentsColumn: 'В этой группе инцидентов пока нет.',
  readOnly: 'Только просмотр',
  readOnlyMode: 'Сейчас доступен только просмотр',
  backendActionsActive: 'Действия оператора доступны',
  saveAction: 'Зафиксировать действие',
  readOnlyCta: 'Фиксация временно недоступна',
  operatorNote: 'Комментарий оператора',
  escalationHandoff: 'Передача на разбор',
  closureSummary: 'Итог решения',
  relatedEvents: 'Связанные события',
  actionsTaken: 'Что уже сделал оператор',
  noActionsYet: 'Явных действий оператора пока нет. Экран не будет показывать неподтверждённые шаги.',
};

export const SESSION_COPY = {
  detailsPanel: 'Детали сессии',
  sessionFlow: 'Ход сессии',
  lifecycleSummary: 'Ключевые этапы сессии',
  operatorContext: 'Контекст для оператора',
  operatorActions: 'Действия оператора',
  emptyDetailsTitle: 'Выберите сессию',
  emptyDetailsText: 'Откройте любую строку в активном блоке или журнале, чтобы увидеть этапы сессии, состояние системы и действия оператора.',
  emptyList: 'По выбранным фильтрам сессии не найдены.',
  emptyActive: 'По текущим фильтрам активных сессий нет.',
  openDetailsHint: 'Открывайте любую строку справа в деталях сессии без переключения режимов.',
  cardUidVisitId: 'Карта / UID / номер сессии',
  cardUidVisitPlaceholder: 'UID карты или номер сессии',
  completionReason: 'Причина завершения',
  zeroVolumeAbortOnly: 'Только прерывания без налива',
};

export const TAP_COPY = {
  tapNumber: 'Кран №',
  liveState: 'Текущее состояние',
  liveSignals: 'Сигналы системы',
  sessionAndGuest: 'Текущая сессия',
  noSession: 'Сейчас у крана нет открытой сессии',
  openSession: 'Открыть детали сессии',
  openTap: 'Перейти к крану',
  openSessionHistory: 'Открыть историю сессии',
  openIncident: 'Открыть инцидент',
  noRecentEvents: 'По этому крану пока нет недавних событий.',
  activeSessionCard: 'Активная сессия / карта',
  reader: 'Считыватель',
  screen: 'Экран',
  connectivityOnline: 'На связи',
  connectivityOffline: 'Нет связи',
  backendNoData: 'Нет данных от системы',
  operatorActionsTitle: 'Операторские действия',
  serviceActionsTitle: 'Сервисные действия',
  lockTap: 'Заблокировать кран',
  unlockTap: 'Разблокировать кран',
  controller: 'Контроллер',
  display: 'Экран',
  keySignal: 'Ключевой сигнал',
  lockAt: 'Блокировка с',
  waitingForLock: 'Ожидает блокировку',
  heartbeat: 'Heartbeat',
  sync: 'Синхронизация',
};

export const COMMON_COPY = {
  system: 'Система',
  impact: 'Влияние',
  refresh: 'Обновить',
  apply: 'Применить',
  reset: 'Сбросить',
};

export const SHELL_COPY = {
  operationalSummaryEyebrow: 'Операционная сводка',
  operationalSummaryAria: 'Единая панель операционной сводки',
  guestContext: 'Контекст гостя',
  logout: 'Выйти',
  syncClean: 'Синхронизация: чисто',
  syncUnsynced: (count) => `Синхронизация: ${count} несинхр.`,
  syncOfflineQueue: (count) => `Очередь синхронизации: ${count} офлайн`,
  syncUnsyncedTitle: 'Есть локальные проливы, ожидающие синхронизации с бэкендом.',
  syncOfflineTitle: 'Есть устройства с локальными/офлайн проблемами, влияющими на оперативную синхронизацию.',
  syncCleanTitle: 'Несинхронизированных проливов и офлайн-хвостов не обнаружено.',
};

export const TAP_SCREENS_COPY = {
  guestFacingOverrideLoadError: 'Не удалось загрузить гостевое переопределение.',
  managementOnlySettings: 'Настройки экрана доступны только ролям управления и инженерии.',
  introText: 'Ниже видно, какой сценарий, брендирование и текущее состояние сейчас видит гость на каждом экране крана.',
  sectionHint: 'Карточка сразу собирает сводку из состояния крана, переопределения экрана и полей напитка/дисплея — без открытия модального окна.',
  tapLabel: 'Кран',
  previewAria: (name) => `Гостевой предпросмотр: ${name}`,
  displayEnabled: 'Экран крана включён',
  displayDisabled: 'Экран крана выключен',
  guestScenario: 'Текущий гостевой сценарий',
  brandingSummary: 'Сводка брендирования',
  displayRuntime: 'Состояние экрана',
  controller: 'Контроллер',
  operatorNote: 'Комментарий оператора',
  operatorSummary: 'Сводка для оператора',
  overrideSummaryUnavailable: 'Сводка переопределения недоступна',
};

