export const OPERATOR_TERMS = {
  visit: 'визит',
  pour: 'налив',
  incident: 'инцидент',
  tap: 'кран',
  system: 'система',
  reader: 'считыватель',
  screen: 'экран',
};

export const INCIDENT_COPY = {
  actionForm: 'Зафиксировать действие',
  actionFormTitle: 'Действие по инциденту',
  actionLayer: 'Операторские действия',
  detailsPanel: 'Детали инцидента',
  systemLabel: 'Система',
  impact: 'Влияние',
  owner: 'Ответственный оператор',
  ownerServer: 'Ответственный в системе',
  stateFlow: 'Ход инцидента',
  openDetails: 'Открыть детали',
  openTap: 'Открыть кран',
  openSession: 'Открыть визит',
  openSystem: 'Открыть систему',
  refreshQueue: 'Обновить очередь',
  noIncidentsFiltered: 'По выбранным условиям инциденты не найдены.',
  noIncidentsColumn: 'В этой группе инцидентов пока нет.',
  readOnly: 'Только просмотр',
  readOnlyMode: 'Сейчас доступен только просмотр',
  backendActionsActive: 'Действия оператора доступны',
  saveAction: 'Сохранить действие',
  readOnlyCta: 'Фиксация временно недоступна',
  operatorNote: 'Комментарий оператора',
  escalationHandoff: 'Передача на разбор',
  closureSummary: 'Итог решения',
  relatedEvents: 'Связанные события',
  actionsTaken: 'Что уже сделал оператор',
  noActionsYet: 'Подтверждённых действий по инциденту пока нет.',
};

export const SESSION_COPY = {
  detailsPanel: 'Детали визита',
  sessionFlow: 'Ход визита',
  lifecycleSummary: 'Ключевые этапы визита',
  operatorContext: 'Контекст для оператора',
  operatorActions: 'Действия оператора',
  emptyDetailsTitle: 'Выберите визит',
  emptyDetailsText: 'Откройте строку в активном блоке или журнале, чтобы увидеть этапы визита, состояние системы и действия оператора.',
  emptyList: 'По выбранным фильтрам визиты не найдены.',
  emptyActive: 'По текущим фильтрам активных визитов нет.',
  openDetailsHint: 'Открывайте любую строку справа, чтобы видеть детали визита без переключения экранов.',
  cardUidVisitId: 'Карта / UID / номер визита',
  cardUidVisitPlaceholder: 'UID карты или номер визита',
  completionReason: 'Причина завершения',
  zeroVolumeAbortOnly: 'Только прерывания без налива',
};

export const TAP_COPY = {
  tapNumber: 'Кран №',
  liveState: 'Текущее состояние',
  liveSignals: 'Сигналы системы',
  sessionAndGuest: 'Активный визит',
  noSession: 'Сейчас у крана нет активного визита',
  openSession: 'Открыть визит',
  openTap: 'Открыть кран',
  openSessionHistory: 'Открыть историю визита',
  openIncident: 'Открыть инцидент',
  noRecentEvents: 'По этому крану пока нет недавних событий.',
  activeSessionCard: 'Визит / карта',
  reader: 'Считыватель',
  screen: 'Экран',
  connectivityOnline: 'На связи',
  connectivityOffline: 'Нет связи',
  backendNoData: 'Нет данных от системы',
  operatorActionsTitle: 'Операторские действия',
  serviceActionsTitle: 'Сервисные действия',
  lockTap: 'Заблокировать кран',
  unlockTap: 'Разблокировать кран',
  controller: 'Контроллер',
  display: 'Экран',
  keySignal: 'Ключевой сигнал',
  lockAt: 'Блокировка с',
  waitingForLock: 'Ожидает блокировку',
  heartbeat: 'Последний сигнал',
  sync: 'Синхронизация',
};

export const COMMON_COPY = {
  system: 'Система',
  impact: 'Влияние',
  refresh: 'Обновить',
  apply: 'Применить',
  reset: 'Сбросить',
};

export const SHELL_COPY = {
  operationalSummaryEyebrow: 'Операционная сводка',
  operationalSummaryAria: 'Единая панель операционной сводки',
  guestContext: 'Контекст гостя',
  logout: 'Выйти',
  syncClean: 'Синхронизация: чисто',
  syncUnsynced: (count) => `Синхронизация: ${count} ждут подтверждения`,
  syncOfflineQueue: (count) => `Очередь синхронизации: ${count} вне связи`,
  syncUnsyncedTitle: 'Есть локальные наливы, ожидающие синхронизации с системой.',
  syncOfflineTitle: 'Есть устройства с локальными или офлайн-проблемами, влияющими на оперативную синхронизацию.',
  syncCleanTitle: 'Несинхронизированных наливов и офлайн-хвостов не обнаружено.',
};

export const TAP_SCREENS_COPY = {
  guestFacingOverrideLoadError: 'Не удалось загрузить настройки гостевого экрана.',
  managementOnlySettings: 'Настройки экрана доступны только управленческим и инженерным ролям.',
  introText: 'Ниже видно, какой сценарий, брендинг и текущее состояние сейчас видит гость на каждом экране крана.',
  sectionHint: 'Карточка собирает сводку из состояния крана, настроек экрана и полей напитка без открытия модального окна.',
  tapLabel: 'Кран',
  previewAria: (name) => `Гостевой предпросмотр: ${name}`,
  displayEnabled: 'Экран крана включён',
  displayDisabled: 'Экран крана выключен',
  guestScenario: 'Текущий гостевой сценарий',
  brandingSummary: 'Сводка брендинга',
  displayRuntime: 'Состояние экрана',
  controller: 'Контроллер',
  operatorNote: 'Комментарий оператора',
  operatorSummary: 'Сводка для оператора',
  overrideSummaryUnavailable: 'Сводка настроек экрана недоступна',
};
