"""Initial schema from models

Revision ID: a04b8900ce88
Revises: 
Create Date: 2026-02-09 13:21:03.357815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a04b8900ce88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True, comment='ID пользователя, совершившего действие'),
    sa.Column('action', sa.String(), nullable=False, comment="Тип действия, e.g., 'create_keg'"),
    sa.Column('target_entity', sa.String(), nullable=True, comment="Сущность, над которой совершено действие, e.g., 'Keg'"),
    sa.Column('target_id', sa.String(), nullable=True, comment='ID целевой сущности'),
    sa.Column('details', sa.Text(), nullable=True, comment='Детали действия в формате JSON'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('beverages',
    sa.Column('beverage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Название напитка, e.g., 'Heineken'"),
    sa.Column('brewery', sa.String(length=100), nullable=True, comment='Пивоварня'),
    sa.Column('style', sa.String(length=50), nullable=True, comment="Стиль, e.g., 'Lager', 'IPA'"),
    sa.Column('abv', sa.Numeric(precision=4, scale=2), nullable=True, comment='Крепость (Alcohol By Volume)'),
    sa.Column('sell_price_per_liter', sa.Numeric(precision=10, scale=2), nullable=False, comment='Розничная цена за литр'),
    sa.PrimaryKeyConstraint('beverage_id')
    )
    op.create_index(op.f('ix_beverages_name'), 'beverages', ['name'], unique=True)
    op.create_table('controllers',
    sa.Column('controller_id', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='Текущий IP-адрес устройства в сети'),
    sa.Column('firmware_version', sa.String(length=20), nullable=True, comment='Версия прошивки на устройстве'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Время первой регистрации контроллера'),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment="Время последнего 'check-in' от контроллера"),
    sa.PrimaryKeyConstraint('controller_id')
    )
    op.create_index(op.f('ix_controllers_controller_id'), 'controllers', ['controller_id'], unique=False)
    op.create_table('system_states',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_states_key'), 'system_states', ['key'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма транзакции. Положительная для пополнения.'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Тип: top-up, refund, correction'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='Метод оплаты: cash, card'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_guest_id'), 'transactions', ['guest_id'], unique=False)
    op.alter_column('cards', 'card_uid',
               existing_type=sa.VARCHAR(length=50),
               comment='Уникальный идентификатор, читаемый с карты',
               existing_nullable=False)
    op.alter_column('cards', 'guest_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cards', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус: active, inactive, lost',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_cards_guest_id'), table_name='cards')
    op.create_index(op.f('ix_cards_guest_id'), 'cards', ['guest_id'], unique=False)
    op.create_index(op.f('ix_cards_status'), 'cards', ['status'], unique=False)
    op.drop_constraint(op.f('fk_guest'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'guests', ['guest_id'], ['guest_id'])
    op.alter_column('guests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('guests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('guests_id_document_key'), 'guests', type_='unique')
    op.create_index(op.f('ix_guests_id_document'), 'guests', ['id_document'], unique=False)
    op.create_index(op.f('ix_guests_last_name'), 'guests', ['last_name'], unique=False)
    op.add_column('kegs', sa.Column('beverage_id', sa.UUID(), nullable=False))
    op.add_column('kegs', sa.Column('status', sa.String(length=20), nullable=False, comment='Статус: full, in_use, empty'))
    op.alter_column('kegs', 'initial_volume_ml',
               existing_type=sa.INTEGER(),
               comment='Начальный объем в миллилитрах',
               existing_nullable=False)
    op.alter_column('kegs', 'current_volume_ml',
               existing_type=sa.INTEGER(),
               comment='Текущий остаток в миллилитрах',
               existing_nullable=False)
    op.alter_column('kegs', 'purchase_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               comment='Закупочная стоимость всей кеги')
    op.alter_column('kegs', 'tapped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время подключения к крану',
               existing_nullable=True)
    op.alter_column('kegs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время, когда кега закончилась',
               existing_nullable=True)
    op.alter_column('kegs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_kegs_beverage_id'), 'kegs', ['beverage_id'], unique=False)
    op.create_index(op.f('ix_kegs_status'), 'kegs', ['status'], unique=False)
    op.create_foreign_key(None, 'kegs', 'beverages', ['beverage_id'], ['beverage_id'])
    op.drop_column('kegs', 'abv')
    op.drop_column('kegs', 'beer_name')
    op.drop_column('kegs', 'beer_style')
    op.drop_column('kegs', 'brewery')
    op.alter_column('pours', 'client_tx_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Идентификатор от RPi для идемпотентности',
               existing_nullable=False)
    op.alter_column('pours', 'amount_charged',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Списанная сумма',
               existing_nullable=False)
    op.alter_column('pours', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pours_client_tx_id'), table_name='pours')
    op.drop_index(op.f('idx_pours_guest_id'), table_name='pours')
    op.drop_index(op.f('idx_pours_tap_id'), table_name='pours')
    op.drop_constraint(op.f('pours_client_tx_id_key'), 'pours', type_='unique')
    op.create_index(op.f('ix_pours_card_uid'), 'pours', ['card_uid'], unique=False)
    op.create_index(op.f('ix_pours_client_tx_id'), 'pours', ['client_tx_id'], unique=True)
    op.create_index(op.f('ix_pours_guest_id'), 'pours', ['guest_id'], unique=False)
    op.create_index(op.f('ix_pours_keg_id'), 'pours', ['keg_id'], unique=False)
    op.drop_column('pours', 'price_per_ml_at_pour')
    op.add_column('taps', sa.Column('status', sa.String(length=20), nullable=False, comment='Статус: active, locked, cleaning, empty'))
    op.alter_column('taps', 'display_name',
               existing_type=sa.VARCHAR(length=50),
               comment="Имя крана для UI, e.g., 'Кран 1'",
               existing_nullable=False)
    op.create_index(op.f('ix_taps_status'), 'taps', ['status'], unique=False)
    op.create_unique_constraint(None, 'taps', ['display_name'])
    op.create_unique_constraint(None, 'taps', ['keg_id'])
    op.drop_constraint(op.f('fk_keg'), 'taps', type_='foreignkey')
    op.create_foreign_key(None, 'taps', 'kegs', ['keg_id'], ['keg_id'])
    op.drop_column('taps', 'price_per_ml')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taps', sa.Column('price_per_ml', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'taps', type_='foreignkey')
    op.create_foreign_key(op.f('fk_keg'), 'taps', 'kegs', ['keg_id'], ['keg_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'taps', type_='unique')
    op.drop_constraint(None, 'taps', type_='unique')
    op.drop_index(op.f('ix_taps_status'), table_name='taps')
    op.alter_column('taps', 'display_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Имя крана для UI, e.g., 'Кран 1'",
               existing_nullable=False)
    op.drop_column('taps', 'status')
    op.add_column('pours', sa.Column('price_per_ml_at_pour', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_pours_keg_id'), table_name='pours')
    op.drop_index(op.f('ix_pours_guest_id'), table_name='pours')
    op.drop_index(op.f('ix_pours_client_tx_id'), table_name='pours')
    op.drop_index(op.f('ix_pours_card_uid'), table_name='pours')
    op.create_unique_constraint(op.f('pours_client_tx_id_key'), 'pours', ['client_tx_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pours_tap_id'), 'pours', ['tap_id'], unique=False)
    op.create_index(op.f('idx_pours_guest_id'), 'pours', ['guest_id'], unique=False)
    op.create_index(op.f('idx_pours_client_tx_id'), 'pours', ['client_tx_id'], unique=False)
    op.alter_column('pours', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pours', 'amount_charged',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Списанная сумма',
               existing_nullable=False)
    op.alter_column('pours', 'client_tx_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Идентификатор от RPi для идемпотентности',
               existing_nullable=False)
    op.add_column('kegs', sa.Column('brewery', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('kegs', sa.Column('beer_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('kegs', sa.Column('beer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('kegs', sa.Column('abv', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'kegs', type_='foreignkey')
    op.drop_index(op.f('ix_kegs_status'), table_name='kegs')
    op.drop_index(op.f('ix_kegs_beverage_id'), table_name='kegs')
    op.alter_column('kegs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kegs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время, когда кега закончилась',
               existing_nullable=True)
    op.alter_column('kegs', 'tapped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время подключения к крану',
               existing_nullable=True)
    op.alter_column('kegs', 'purchase_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment=None,
               existing_comment='Закупочная стоимость всей кеги')
    op.alter_column('kegs', 'current_volume_ml',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Текущий остаток в миллилитрах',
               existing_nullable=False)
    op.alter_column('kegs', 'initial_volume_ml',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Начальный объем в миллилитрах',
               existing_nullable=False)
    op.drop_column('kegs', 'status')
    op.drop_column('kegs', 'beverage_id')
    op.drop_index(op.f('ix_guests_last_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_id_document'), table_name='guests')
    op.create_unique_constraint(op.f('guests_id_document_key'), 'guests', ['id_document'], postgresql_nulls_not_distinct=False)
    op.alter_column('guests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('guests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('fk_guest'), 'cards', 'guests', ['guest_id'], ['guest_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cards_status'), table_name='cards')
    op.drop_index(op.f('ix_cards_guest_id'), table_name='cards')
    op.create_index(op.f('idx_cards_guest_id'), 'cards', ['guest_id'], unique=False)
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cards', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Статус: active, inactive, lost',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('cards', 'guest_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cards', 'card_uid',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Уникальный идентификатор, читаемый с карты',
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_guest_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_system_states_key'), table_name='system_states')
    op.drop_table('system_states')
    op.drop_index(op.f('ix_controllers_controller_id'), table_name='controllers')
    op.drop_table('controllers')
    op.drop_index(op.f('ix_beverages_name'), table_name='beverages')
    op.drop_table('beverages')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
