"""Initial schema from models

Revision ID: d42e26e5d277
Revises: 
Create Date: 2025-11-08 20:03:18.959929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42e26e5d277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True, comment='ID пользователя, совершившего действие'),
    sa.Column('action', sa.String(), nullable=False, comment="Тип действия, e.g., 'create_keg'"),
    sa.Column('target_entity', sa.String(), nullable=True, comment="Сущность, над которой совершено действие, e.g., 'Keg'"),
    sa.Column('target_id', sa.String(), nullable=True, comment='ID целевой сущности'),
    sa.Column('details', sa.Text(), nullable=True, comment='Детали действия в формате JSON'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('beverages',
    sa.Column('beverage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Название напитка, e.g., 'Heineken'"),
    sa.Column('brewery', sa.String(length=100), nullable=True, comment='Пивоварня'),
    sa.Column('style', sa.String(length=50), nullable=True, comment="Стиль, e.g., 'Lager', 'IPA'"),
    sa.Column('abv', sa.Numeric(precision=4, scale=2), nullable=True, comment='Крепость (Alcohol By Volume)'),
    sa.Column('sell_price_per_liter', sa.Numeric(precision=10, scale=2), nullable=False, comment='Розничная цена за литр'),
    sa.PrimaryKeyConstraint('beverage_id')
    )
    op.create_index(op.f('ix_beverages_name'), 'beverages', ['name'], unique=True)
    op.create_table('controllers',
    sa.Column('controller_id', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='Текущий IP-адрес устройства в сети'),
    sa.Column('firmware_version', sa.String(length=20), nullable=True, comment='Версия прошивки на устройстве'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Время первой регистрации контроллера'),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment="Время последнего 'check-in' от контроллера"),
    sa.PrimaryKeyConstraint('controller_id')
    )
    op.create_index(op.f('ix_controllers_controller_id'), 'controllers', ['controller_id'], unique=False)
    op.create_table('guests',
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('id_document', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('guest_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_guests_id_document'), 'guests', ['id_document'], unique=False)
    op.create_index(op.f('ix_guests_last_name'), 'guests', ['last_name'], unique=False)
    op.create_table('system_states',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_states_key'), 'system_states', ['key'], unique=False)
    op.create_table('cards',
    sa.Column('card_uid', sa.String(length=50), nullable=False, comment='Уникальный идентификатор, читаемый с карты'),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус: active, inactive, lost'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.PrimaryKeyConstraint('card_uid')
    )
    op.create_index(op.f('ix_cards_guest_id'), 'cards', ['guest_id'], unique=False)
    op.create_index(op.f('ix_cards_status'), 'cards', ['status'], unique=False)
    op.create_table('kegs',
    sa.Column('keg_id', sa.UUID(), nullable=False),
    sa.Column('beverage_id', sa.UUID(), nullable=False),
    sa.Column('initial_volume_ml', sa.Integer(), nullable=False, comment='Начальный объем в миллилитрах'),
    sa.Column('current_volume_ml', sa.Integer(), nullable=False, comment='Текущий остаток в миллилитрах'),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Закупочная стоимость всей кеги'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус: full, in_use, empty'),
    sa.Column('tapped_at', sa.DateTime(timezone=True), nullable=True, comment='Время подключения к крану'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Время, когда кега закончилась'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverages.beverage_id'], ),
    sa.PrimaryKeyConstraint('keg_id')
    )
    op.create_index(op.f('ix_kegs_beverage_id'), 'kegs', ['beverage_id'], unique=False)
    op.create_index(op.f('ix_kegs_status'), 'kegs', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма транзакции. Положительная для пополнения.'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Тип: top-up, refund, correction'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='Метод оплаты: cash, card'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_guest_id'), 'transactions', ['guest_id'], unique=False)
    op.create_table('taps',
    sa.Column('tap_id', sa.Integer(), nullable=False),
    sa.Column('keg_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment="Имя крана для UI, e.g., 'Кран 1'"),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус: active, locked, cleaning, empty'),
    sa.Column('last_cleaned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['keg_id'], ['kegs.keg_id'], ),
    sa.PrimaryKeyConstraint('tap_id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('keg_id')
    )
    op.create_index(op.f('ix_taps_status'), 'taps', ['status'], unique=False)
    op.create_table('pours',
    sa.Column('pour_id', sa.UUID(), nullable=False),
    sa.Column('client_tx_id', sa.String(length=100), nullable=False, comment='Идентификатор от RPi для идемпотентности'),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=50), nullable=False),
    sa.Column('tap_id', sa.Integer(), nullable=False),
    sa.Column('keg_id', sa.UUID(), nullable=False),
    sa.Column('volume_ml', sa.Integer(), nullable=False),
    sa.Column('amount_charged', sa.Numeric(precision=10, scale=2), nullable=False, comment='Списанная сумма'),
    sa.Column('poured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_uid'], ['cards.card_uid'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.ForeignKeyConstraint(['keg_id'], ['kegs.keg_id'], ),
    sa.ForeignKeyConstraint(['tap_id'], ['taps.tap_id'], ),
    sa.PrimaryKeyConstraint('pour_id')
    )
    op.create_index(op.f('ix_pours_card_uid'), 'pours', ['card_uid'], unique=False)
    op.create_index(op.f('ix_pours_client_tx_id'), 'pours', ['client_tx_id'], unique=True)
    op.create_index(op.f('ix_pours_guest_id'), 'pours', ['guest_id'], unique=False)
    op.create_index(op.f('ix_pours_keg_id'), 'pours', ['keg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pours_keg_id'), table_name='pours')
    op.drop_index(op.f('ix_pours_guest_id'), table_name='pours')
    op.drop_index(op.f('ix_pours_client_tx_id'), table_name='pours')
    op.drop_index(op.f('ix_pours_card_uid'), table_name='pours')
    op.drop_table('pours')
    op.drop_index(op.f('ix_taps_status'), table_name='taps')
    op.drop_table('taps')
    op.drop_index(op.f('ix_transactions_guest_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_kegs_status'), table_name='kegs')
    op.drop_index(op.f('ix_kegs_beverage_id'), table_name='kegs')
    op.drop_table('kegs')
    op.drop_index(op.f('ix_cards_status'), table_name='cards')
    op.drop_index(op.f('ix_cards_guest_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_system_states_key'), table_name='system_states')
    op.drop_table('system_states')
    op.drop_index(op.f('ix_guests_last_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_id_document'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_controllers_controller_id'), table_name='controllers')
    op.drop_table('controllers')
    op.drop_index(op.f('ix_beverages_name'), table_name='beverages')
    op.drop_table('beverages')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
