name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - docs/mvp-packaging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install mkdocs & material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      - name: Build and Deploy
        run: |
          mkdocs build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
